-- Insert 10 categories
INSERT INTO "news_categories" ("name", "slug") VALUES 
('Công nghệ', 'technology'),
('Tài chính', 'finance'),
('Thể thao', 'sports'),
('Giải trí', 'entertainment'),
('Sức khỏe', 'health'),
('Du lịch', 'travel'),
('Giáo dục', 'education'),
('Môi trường', 'environment'),
('Chính trị', 'politics'),
('Văn hóa', 'culture');

-- Insert 101 news records
INSERT INTO "news" ("title", "content", "author", "category_id", "imageUrl") VALUES 
('AI ChatGPT ra mắt phiên bản mới', 'OpenAI vừa công bố phiên bản ChatGPT mới với nhiều tính năng cải tiến đáng chú ý...', 'Nguyễn Văn A', 1, 'https://via.placeholder.com/400x200'),
('Thị trường crypto biến động mạnh', 'Bitcoin và các đồng tiền điện tử khác có những biến động lớn trong tuần qua...', 'Trần Thị B', 2, 'https://via.placeholder.com/400x200'),
('World Cup 2024 sắp diễn ra', 'Giải bóng đá World Cup 2024 sẽ được tổ chức tại nhiều quốc gia...', 'Lê Văn C', 3, 'https://via.placeholder.com/400x200'),
('Phim mới của Marvel ra rạp', 'Bộ phim siêu anh hùng mới nhất của Marvel đã chính thức ra mắt...', 'Phạm Thị D', 4, 'https://via.placeholder.com/400x200'),
('Vaccine COVID-19 thế hệ mới', 'Các nhà khoa học đã phát triển thành công vaccine COVID-19 thế hệ mới...', 'Hoàng Văn E', 5, 'https://via.placeholder.com/400x200'),
('Du lịch Việt Nam hồi phục mạnh', 'Ngành du lịch Việt Nam đang có dấu hiệu hồi phục tích cực sau đại dịch...', 'Vũ Thị F', 6, 'https://via.placeholder.com/400x200'),
('Cải cách giáo dục đại học', 'Bộ Giáo dục đang triển khai kế hoạch cải cách toàn diện hệ thống giáo dục...', 'Đỗ Văn G', 7, 'https://via.placeholder.com/400x200'),
('Biến đổi khí hậu tác động nghiêm trọng', 'Báo cáo mới nhất cho thấy biến đổi khí hậu đang có tác động nghiêm trọng...', 'Bùi Thị H', 8, 'https://via.placeholder.com/400x200'),
('Chính sách kinh tế mới được thông qua', 'Quốc hội đã thông qua gói chính sách kinh tế mới nhằm thúc đẩy tăng trưởng...', 'Cao Văn I', 9, 'https://via.placeholder.com/400x200'),
('Lễ hội văn hóa truyền thống', 'Lễ hội văn hóa truyền thống sẽ được tổ chức tại nhiều địa phương...', 'Đinh Thị K', 10, 'https://via.placeholder.com/400x200'),
('Smartphone 5G giá rẻ ra mắt', 'Các hãng công nghệ đang tung ra thị trường những chiếc smartphone 5G với giá cả phải chăng...', 'Nguyễn Văn L', 1, 'https://via.placeholder.com/400x200'),
('Ngân hàng tăng lãi suất', 'Nhiều ngân hàng lớn đã quyết định tăng lãi suất tiền gửi và cho vay...', 'Trần Thị M', 2, 'https://via.placeholder.com/400x200'),
('SEA Games 2024 chuẩn bị khai mạc', 'Đoàn thể thao Việt Nam đang tích cực chuẩn bị cho SEA Games 2024...', 'Lê Văn N', 3, 'https://via.placeholder.com/400x200'),
('Concert âm nhạc quốc tế', 'Nhiều nghệ sĩ quốc tế nổi tiếng sẽ tham gia concert âm nhạc tại Việt Nam...', 'Phạm Thị O', 4, 'https://via.placeholder.com/400x200'),
('Thuốc điều trị ung thư mới', 'Các nhà khoa học đã phát triển thành công loại thuốc điều trị ung thư hiệu quả...', 'Hoàng Văn P', 5, 'https://via.placeholder.com/400x200'),
('Khu du lịch sinh thái mới', 'Khu du lịch sinh thái mới được xây dựng với tiêu chuẩn quốc tế...', 'Vũ Thị Q', 6, 'https://via.placeholder.com/400x200'),
('Chương trình học bổng du học', 'Chính phủ công bố chương trình học bổng du học mới cho sinh viên...', 'Đỗ Văn R', 7, 'https://via.placeholder.com/400x200'),
('Dự án năng lượng tái tạo', 'Dự án năng lượng tái tạo lớn nhất khu vực sắp được khởi công...', 'Bùi Thị S', 8, 'https://via.placeholder.com/400x200'),
('Hội nghị thượng đỉnh ASEAN', 'Hội nghị thượng đỉnh ASEAN sẽ được tổ chức tại Việt Nam...', 'Cao Văn T', 9, 'https://via.placeholder.com/400x200'),
('Bảo tàng nghệ thuật hiện đại', 'Bảo tàng nghệ thuật hiện đại mới sẽ được khai trương trong tháng tới...', 'Đinh Thị U', 10, 'https://via.placeholder.com/400x200'),
('Công nghệ blockchain trong ngân hàng', 'Các ngân hàng đang ứng dụng công nghệ blockchain để cải thiện dịch vụ...', 'Nguyễn Văn V', 1, 'https://via.placeholder.com/400x200'),
('Quỹ đầu tư mạo hiểm mới', 'Quỹ đầu tư mạo hiểm mới được thành lập với vốn điều lệ 100 triệu USD...', 'Trần Thị W', 2, 'https://via.placeholder.com/400x200'),
('Giải tennis quốc tế', 'Giải tennis quốc tế sẽ được tổ chức tại Việt Nam lần đầu tiên...', 'Lê Văn X', 3, 'https://via.placeholder.com/400x200'),
('Phim Việt Nam đoạt giải quốc tế', 'Bộ phim Việt Nam vừa đoạt giải thưởng tại liên hoan phim quốc tế...', 'Phạm Thị Y', 4, 'https://via.placeholder.com/400x200'),
('Bệnh viện thông minh đầu tiên', 'Bệnh viện thông minh đầu tiên tại Việt Nam sắp đi vào hoạt động...', 'Hoàng Văn Z', 5, 'https://via.placeholder.com/400x200'),
('Tour du lịch vũ trụ', 'Công ty du lịch vũ trụ đầu tiên tại Việt Nam vừa được thành lập...', 'Vũ Thị AA', 6, 'https://via.placeholder.com/400x200'),
('Trường đại học quốc tế mới', 'Trường đại học quốc tế mới sẽ được xây dựng tại TP.HCM...', 'Đỗ Văn BB', 7, 'https://via.placeholder.com/400x200'),
('Rừng nhiệt đới được bảo vệ', 'Chương trình bảo vệ rừng nhiệt đới mới được triển khai trên toàn quốc...', 'Bùi Thị CC', 8, 'https://via.placeholder.com/400x200'),
('Luật mới về an ninh mạng', 'Luật an ninh mạng mới được Quốc hội thông qua với nhiều quy định mới...', 'Cao Văn DD', 9, 'https://via.placeholder.com/400x200'),
('Lễ hội ẩm thực quốc tế', 'Lễ hội ẩm thực quốc tế sẽ được tổ chức tại Hà Nội trong tháng tới...', 'Đinh Thị EE', 10, 'https://via.placeholder.com/400x200'),
('Robot AI phục vụ nhà hàng', 'Nhà hàng đầu tiên sử dụng robot AI để phục vụ khách hàng...', 'Nguyễn Văn FF', 1, 'https://via.placeholder.com/400x200'),
('Sàn giao dịch chứng khoán mới', 'Sàn giao dịch chứng khoán mới sẽ được thành lập để phục vụ doanh nghiệp nhỏ...', 'Trần Thị GG', 2, 'https://via.placeholder.com/400x200'),
('Đội tuyển bóng chuyền vô địch', 'Đội tuyển bóng chuyền nữ Việt Nam vừa giành chức vô địch khu vực...', 'Lê Văn HH', 3, 'https://via.placeholder.com/400x200'),
('Game show truyền hình mới', 'Game show truyền hình mới với format độc đáo sắp lên sóng...', 'Phạm Thị II', 4, 'https://via.placeholder.com/400x200'),
('Phương pháp điều trị mới', 'Phương pháp điều trị mới cho bệnh tim mạch được áp dụng thành công...', 'Hoàng Văn JJ', 5, 'https://via.placeholder.com/400x200'),
('Khu nghỉ dưỡng cao cấp', 'Khu nghỉ dưỡng cao cấp mới được xây dựng tại Phú Quốc...', 'Vũ Thị KK', 6, 'https://via.placeholder.com/400x200'),
('Khóa học trực tuyến miễn phí', 'Nền tảng giáo dục trực tuyến ra mắt khóa học miễn phí cho học sinh...', 'Đỗ Văn LL', 7, 'https://via.placeholder.com/400x200'),
('Dự án thành phố xanh', 'Dự án thành phố xanh đầu tiên tại Việt Nam được khởi động...', 'Bùi Thị MM', 8, 'https://via.placeholder.com/400x200'),
('Chính sách hỗ trợ startup', 'Chính phủ công bố chính sách hỗ trợ mới cho các startup công nghệ...', 'Cao Văn NN', 9, 'https://via.placeholder.com/400x200'),
('Triển lãm nghệ thuật đương đại', 'Triển lãm nghệ thuật đương đại lớn nhất năm sắp được khai mạc...', 'Đinh Thị OO', 10, 'https://via.placeholder.com/400x200'),
('Xe điện tự lái thử nghiệm', 'Xe điện tự lái đầu tiên được thử nghiệm trên đường phố Việt Nam...', 'Nguyễn Văn PP', 1, 'https://via.placeholder.com/400x200'),
('Fintech Việt Nam phát triển mạnh', 'Ngành fintech Việt Nam đang có sự phát triển mạnh mẽ với nhiều sản phẩm mới...', 'Trần Thị QQ', 2, 'https://via.placeholder.com/400x200'),
('Marathon quốc tế Việt Nam', 'Giải marathon quốc tế Việt Nam thu hút hàng nghìn vận động viên tham gia...', 'Lê Văn RR', 3, 'https://via.placeholder.com/400x200'),
('Liên hoan phim quốc tế', 'Liên hoan phim quốc tế Việt Nam sẽ được tổ chức với sự tham gia của nhiều ngôi sao...', 'Phạm Thị SS', 4, 'https://via.placeholder.com/400x200'),
('Công nghệ gene therapy', 'Công nghệ gene therapy mới được áp dụng để điều trị các bệnh di truyền...', 'Hoàng Văn TT', 5, 'https://via.placeholder.com/400x200'),
('Ứng dụng du lịch thông minh', 'Ứng dụng du lịch thông minh mới giúp du khách khám phá Việt Nam dễ dàng hơn...', 'Vũ Thị UU', 6, 'https://via.placeholder.com/400x200'),
('Chương trình trao đổi sinh viên', 'Chương trình trao đổi sinh viên quốc tế mới được mở rộng...', 'Đỗ Văn VV', 7, 'https://via.placeholder.com/400x200'),
('Khu bảo tồn biển mới', 'Khu bảo tồn biển mới được thành lập để bảo vệ hệ sinh thái biển...', 'Bùi Thị WW', 8, 'https://via.placeholder.com/400x200'),
('Hội nghị ngoại giao đa phương', 'Hội nghị ngoại giao đa phương quan trọng sẽ được tổ chức tại Việt Nam...', 'Cao Văn XX', 9, 'https://via.placeholder.com/400x200'),
('Không gian văn hóa sáng tạo', 'Không gian văn hóa sáng tạo mới được khai trương tại trung tâm thành phố...', 'Đinh Thị YY', 10, 'https://via.placeholder.com/400x200'),
('Công nghệ IoT trong nông nghiệp', 'Công nghệ IoT được ứng dụng rộng rãi trong nông nghiệp thông minh...', 'Nguyễn Văn ZZ', 1, 'https://via.placeholder.com/400x200'),
('Thị trường bất động sản phục hồi', 'Thị trường bất động sản có dấu hiệu phục hồi tích cực trong quý này...', 'Trần Thị AAA', 2, 'https://via.placeholder.com/400x200'),
('Giải bóng đá nữ quốc gia', 'Giải bóng đá nữ quốc gia sẽ được tổ chức với quy mô lớn nhất từ trước đến nay...', 'Lê Văn BBB', 3, 'https://via.placeholder.com/400x200'),
('Chương trình truyền hình thực tế', 'Chương trình truyền hình thực tế mới với concept độc đáo sắp lên sóng...', 'Phạm Thị CCC', 4, 'https://via.placeholder.com/400x200'),
('Bệnh viện tim mạch chuyên khoa', 'Bệnh viện tim mạch chuyên khoa mới được đầu tư xây dựng với công nghệ hiện đại...', 'Hoàng Văn DDD', 5, 'https://via.placeholder.com/400x200'),
('Tuyến du lịch mới khám phá', 'Tuyến du lịch mới giúp du khách khám phá những vùng đất chưa được khai thác...', 'Vũ Thị EEE', 6, 'https://via.placeholder.com/400x200'),
('Hệ thống giáo dục số', 'Hệ thống giáo dục số được triển khai toàn diện trong các trường học...', 'Đỗ Văn FFF', 7, 'https://via.placeholder.com/400x200'),
('Dự án rừng carbon', 'Dự án rừng carbon mới nhằm giảm thiểu khí thải nhà kính...', 'Bùi Thị GGG', 8, 'https://via.placeholder.com/400x200'),
('Chính sách thuế mới', 'Chính sách thuế mới được áp dụng để hỗ trợ doanh nghiệp phát triển...', 'Cao Văn HHH', 9, 'https://via.placeholder.com/400x200'),
('Lễ hội âm nhạc điện tử', 'Lễ hội âm nhạc điện tử quốc tế sẽ được tổ chức tại Việt Nam lần đầu tiên...', 'Đinh Thị III', 10, 'https://via.placeholder.com/400x200'),
('Trí tuệ nhân tạo trong y tế', 'Trí tuệ nhân tạo được ứng dụng để chẩn đoán và điều trị bệnh chính xác hơn...', 'Nguyễn Văn JJJ', 1, 'https://via.placeholder.com/400x200'),
('Sàn thương mại điện tử mới', 'Sàn thương mại điện tử mới ra mắt với nhiều tính năng ưu việt...', 'Trần Thị KKK', 2, 'https://via.placeholder.com/400x200'),
('Giải đua xe F1 tại Việt Nam', 'Giải đua xe F1 có thể sẽ trở lại Việt Nam trong tương lai gần...', 'Lê Văn LLL', 3, 'https://via.placeholder.com/400x200'),
('Phim hoạt hình Việt Nam', 'Phim hoạt hình Việt Nam mới được sản xuất với chất lượng quốc tế...', 'Phạm Thị MMM', 4, 'https://via.placeholder.com/400x200'),
('Vaccine phòng chống cúm mới', 'Vaccine phòng chống cúm thế hệ mới có hiệu quả cao hơn...', 'Hoàng Văn NNN', 5, 'https://via.placeholder.com/400x200'),
('Khu du lịch văn hóa lịch sử', 'Khu du lịch văn hóa lịch sử mới được phát triển để thu hút khách quốc tế...', 'Vũ Thị OOO', 6, 'https://via.placeholder.com/400x200'),
('Trường mầm non quốc tế', 'Trường mầm non quốc tế mới áp dụng phương pháp giáo dục tiên tiến...', 'Đỗ Văn PPP', 7, 'https://via.placeholder.com/400x200'),
('Nhà máy xử lý rác thải', 'Nhà máy xử lý rác thải hiện đại được xây dựng để bảo vệ môi trường...', 'Bùi Thị QQQ', 8, 'https://via.placeholder.com/400x200'),
('Hiệp định thương mại mới', 'Hiệp định thương mại mới được ký kết để thúc đẩy xuất khẩu...', 'Cao Văn RRR', 9, 'https://via.placeholder.com/400x200'),
('Bảo tàng lịch sử quốc gia', 'Bảo tàng lịch sử quốc gia được cải tạo với công nghệ hiện đại...', 'Đinh Thị SSS', 10, 'https://via.placeholder.com/400x200'),
('Công nghệ 6G thử nghiệm', 'Công nghệ 6G được thử nghiệm đầu tiên tại Việt Nam với tốc độ siêu nhanh...', 'Nguyễn Văn TTT', 1, 'https://via.placeholder.com/400x200'),
('Quỹ hưu trí tự nguyện', 'Quỹ hưu trí tự nguyện mới được thành lập để đảm bảo an sinh xã hội...', 'Trần Thị UUU', 2, 'https://via.placeholder.com/400x200'),
('Giải cầu lông quốc tế', 'Giải cầu lông quốc tế Việt Nam Open sẽ được tổ chức với sự tham gia của nhiều tay vợt hàng đầu...', 'Lê Văn VVV', 3, 'https://via.placeholder.com/400x200'),
('Rạp chiếu phim công nghệ cao', 'Rạp chiếu phim công nghệ cao đầu tiên tại Việt Nam sắp được khai trương...', 'Phạm Thị WWW', 4, 'https://via.placeholder.com/400x200'),
('Thuốc điều trị Alzheimer', 'Thuốc điều trị Alzheimer mới cho kết quả khả quan trong thử nghiệm lâm sàng...', 'Hoàng Văn XXX', 5, 'https://via.placeholder.com/400x200'),
('Ứng dụng đặt phòng khách sạn', 'Ứng dụng đặt phòng khách sạn mới với AI giúp tìm kiếm phòng phù hợp nhất...', 'Vũ Thị YYY', 6, 'https://via.placeholder.com/400x200'),
('Chương trình học tiếng Anh miễn phí', 'Chương trình học tiếng Anh miễn phí được triển khai cho học sinh vùng sâu vùng xa...', 'Đỗ Văn ZZZ', 7, 'https://via.placeholder.com/400x200'),
('Khu bảo tồn động vật hoang dã', 'Khu bảo tồn động vật hoang dã mới được thành lập để bảo vệ các loài quý hiếm...', 'Bùi Thị AAAA', 8, 'https://via.placeholder.com/400x200'),
('Hội nghị an ninh khu vực', 'Hội nghị an ninh khu vực sẽ thảo luận về các vấn đề an ninh chung...', 'Cao Văn BBBB', 9, 'https://via.placeholder.com/400x200'),
('Không gian nghệ thuật đương đại', 'Không gian nghệ thuật đương đại mới thu hút nhiều nghệ sĩ trẻ tham gia...', 'Đinh Thị CCCC', 10, 'https://via.placeholder.com/400x200'),
('Drone giao hàng tự động', 'Hệ thống drone giao hàng tự động được thử nghiệm tại các thành phố lớn...', 'Nguyễn Văn DDDD', 1, 'https://via.placeholder.com/400x200'),
('Ngân hàng số hoàn toàn mới', 'Ngân hàng số hoàn toàn mới ra mắt với dịch vụ 100% trực tuyến...', 'Trần Thị EEEE', 2, 'https://via.placeholder.com/400x200'),
('Giải bơi lội quốc gia', 'Giải bơi lội quốc gia sẽ được tổ chức với sự tham gia của các vận động viên hàng đầu...', 'Lê Văn FFFF', 3, 'https://via.placeholder.com/400x200'),
('Show diễn thời trang quốc tế', 'Show diễn thời trang quốc tế sẽ giới thiệu các bộ sưu tập mới nhất...', 'Phạm Thị GGGG', 4, 'https://via.placeholder.com/400x200'),
('Công nghệ chẩn đoán nhanh', 'Công nghệ chẩn đoán nhanh mới giúp phát hiện bệnh trong vài phút...', 'Hoàng Văn HHHH', 5, 'https://via.placeholder.com/400x200'),
('Khu nghỉ dưỡng sinh thái', 'Khu nghỉ dưỡng sinh thái mới được xây dựng theo tiêu chuẩn xanh...', 'Vũ Thị IIII', 6, 'https://via.placeholder.com/400x200'),
('Nền tảng học tập trực tuyến', 'Nền tảng học tập trực tuyến mới với công nghệ VR/AR được ra mắt...', 'Đỗ Văn JJJJ', 7, 'https://via.placeholder.com/400x200'),
('Dự án năng lượng mặt trời', 'Dự án năng lượng mặt trời lớn nhất Việt Nam sắp được khởi công...', 'Bùi Thị KKKK', 8, 'https://via.placeholder.com/400x200'),
('Chính sách hỗ trợ nông dân', 'Chính sách hỗ trợ nông dân mới giúp nâng cao thu nhập và đời sống...', 'Cao Văn LLLL', 9, 'https://via.placeholder.com/400x200'),
('Lễ hội văn học quốc tế', 'Lễ hội văn học quốc tế sẽ quy tụ nhiều nhà văn nổi tiếng thế giới...', 'Đinh Thị MMMM', 10, 'https://via.placeholder.com/400x200'),
('Siêu máy tính AI mới', 'Siêu máy tính AI mới được đưa vào hoạt động để phục vụ nghiên cứu khoa học...', 'Nguyễn Văn NNNN', 1, 'https://via.placeholder.com/400x200'),
('Sàn giao dịch carbon', 'Sàn giao dịch carbon đầu tiên tại Việt Nam sắp đ��ợc thành lập...', 'Trần Thị OOOO', 2, 'https://via.placeholder.com/400x200'),
('Giải golf quốc tế Việt Nam', 'Giải golf quốc tế Việt Nam thu hút sự tham gia của nhiều golfer hàng đầu thế giới...', 'Lê Văn PPPP', 3, 'https://via.placeholder.com/400x200'),
('Chương trình âm nhạc cổ điển', 'Chương trình âm nhạc cổ điển với sự tham gia của dàn nhạc giao hưởng quốc tế...', 'Phạm Thị QQQQ', 4, 'https://via.placeholder.com/400x200'),
('Bệnh viện nhi đồng hiện đại', 'Bệnh viện nhi đồng hiện đại mới được xây dựng với trang thiết bị tiên tiến...', 'Hoàng Văn RRRR', 5, 'https://via.placeholder.com/400x200'),
('Tour du lịch ảo VR', 'Tour du lịch ảo VR cho phép khách hàng khám phá các địa danh nổi tiếng...', 'Vũ Thị SSSS', 6, 'https://via.placeholder.com/400x200'),
('Trường đại học công nghệ', 'Trường đại học công nghệ mới được thành lập với chương trình đào tạo hiện đại...', 'Đỗ Văn TTTT', 7, 'https://via.placeholder.com/400x200'),
('Khu xử lý nước thải', 'Khu xử lý nước thải hiện đại được xây dựng để bảo vệ nguồn nước...', 'Bùi Thị UUUU', 8, 'https://via.placeholder.com/400x200'),
('Hội nghị thượng đỉnh G20', 'Việt Nam được mời tham dự Hội nghị thượng đỉnh G20 với tư cách khách mời...', 'Cao Văn VVVV', 9, 'https://via.placeholder.com/400x200'),
('Triển lãm tranh sơn mài', 'Triển lãm tranh sơn mài Việt Nam thu hút sự quan tâm của giới nghệ thuật quốc tế...', 'Đinh Thị WWWW', 10, 'https://via.placeholder.com/400x200'),
('Công nghệ in 3D y tế', 'Công nghệ in 3D được ứng dụng để tạo ra các bộ phận cơ thể nhân tạo...', 'Nguyễn Văn XXXX', 1, 'https://via.placeholder.com/400x200'),
('Ví điện tử blockchain', 'Ví điện tử blockchain mới ra mắt với tính bảo mật cao và phí giao dịch thấp...', 'Trần Thị YYYY', 2, 'https://via.placeholder.com/400x200'),
('Giải đua thuyền buồm', 'Giải đua thuyền buồm quốc tế sẽ được tổ chức tại vịnh Hạ Long...', 'Lê Văn ZZZZ', 3, 'https://via.placeholder.com/400x200'),
('Lễ trao giải điện ảnh', 'Lễ trao giải điện ảnh Việt Nam sẽ vinh danh những tác phẩm xuất sắc nhất năm...', 'Phạm Thị AAAAA', 4, 'https://via.placeholder.com/400x200'),
('Trung tâm ghép tạng', 'Trung tâm ghép tạng quốc gia mới được thành lập với công nghệ tiên tiến...', 'Hoàng Văn BBBBB', 5, 'https://via.placeholder.com/400x200'),
('Ứng dụng hướng dẫn viên AI', 'Ứng dụng hướng dẫn viên AI giúp du khách tự khám phá các điểm du lịch...', 'Vũ Thị CCCCC', 6, 'https://via.placeholder.com/400x200'),
('Chương trình đào tạo kỹ năng số', 'Chương trình đào tạo kỹ năng số miễn phí cho người lao động...', 'Đỗ Văn DDDDD', 7, 'https://via.placeholder.com/400x200'),
('Khu bảo tồn rừng nguyên sinh', 'Khu bảo tồn rừng nguyên sinh mới được công nhận là di sản thiên nhiên...', 'Bùi Thị EEEEE', 8, 'https://via.placeholder.com/400x200'),
('Chính sách visa mới', 'Chính sách visa mới giúp thu hút đầu tư và du lịch quốc tế...', 'Cao Văn FFFFF', 9, 'https://via.placeholder.com/400x200'),
('Lễ hội múa rối nước', 'Lễ hội múa rối nước truyền thống sẽ được tổ chức quy mô quốc tế...', 'Đinh Thị GGGGG', 10, 'https://via.placeholder.com/400x200'),
('Hệ thống thanh toán không tiền mặt', 'Hệ thống thanh toán không tiền mặt được triển khai rộng rãi trong các thành phố...', 'Nguyễn Văn HHHHH', 1, 'https://via.placeholder.com/400x200');